Controllers/iLcwdMapperController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using iLcwdMapper.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace iLcwdMapper.Controllers

{
    [Route("processors")]
    public class iLcwdMapperController : Controller
    {
        private HomeContext dbContext;
        public iLcwdMapperController(HomeContext context)
        {
            dbContext = context;
        }




        [HttpGet("")]
        public IActionResult Dashboard()
        {
            List<Processor> AllProcessors = dbContext.Processors.ToList();
            ViewBag.ApiKey = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDr42YUsPp9WhD8eoNWXJBpS85Epc0F-xw&callback=myMap";
            return View(AllProcessors);
        }


        [HttpGet("new")]
        public IActionResult New()
        {

            return View();
            
        }

        [HttpGet("destroy/{ProcessorId}")]
        public IActionResult Destroy (int ProcessorId)
        {

            Processor remove = dbContext.Processors.FirstOrDefault(w => w.ProcessorId == ProcessorId);
            dbContext.Processors.Remove(remove);
            dbContext.SaveChanges();
            return RedirectToAction("Dashboard");
            
        }

        [HttpGet("edit/{ProcessorId}")]
        public IActionResult Edit(int ProcessorId)
        {

            Processor RetrievedProcessor = dbContext.Processors.FirstOrDefault(p => p.ProcessorId == ProcessorId);
            return View("Edit", RetrievedProcessor);
            
        }

        [HttpPost("edit/{ProcessorId}")]
        public IActionResult Editit(int ProcessorId, Processor ND)
        {

            if(ModelState.IsValid)
            {
                Processor EditProcessor = dbContext.Processors.FirstOrDefault(p => p.ProcessorId == ProcessorId);
                if(ND.ProcessorAddress != "")
                {
                    EditProcessor.ProcessorAddress = ND.ProcessorAddress;
                }
                if(ND.ProcessorName != "")
                {
                    EditProcessor.ProcessorName = ND.ProcessorName;
                }
                if(ND.ProcessorCounty != "")
                {
                    EditProcessor.ProcessorCounty = ND.ProcessorCounty;
                }
                if(ND.ProcessorCity != "")
                {
                    EditProcessor.ProcessorCity = ND.ProcessorCity;
                }
                if(ND.ProcessorHours != "")
                {
                    EditProcessor.ProcessorHours = ND.ProcessorHours;
                }
                if(ND.LAT != "")
                {
                    EditProcessor.LAT = ND.LAT;
                }
                if(ND.LNG != "")
                {
                    EditProcessor.LNG = ND.LNG;
                }
                EditProcessor.UpdatedAt = DateTime.Now;
                dbContext.SaveChanges();
                List<Processor> AllProcessors = dbContext.Processors.ToList();
                return RedirectToAction("AdminPage");
            }
            else {
                Processor EditProcessor = dbContext.Processors.FirstOrDefault(p => p.ProcessorId == ProcessorId);
                return View ("Edit", EditProcessor);
            }
        
    }



        [HttpPost("create")]
        public IActionResult Create(Processor processor)
        {

                if(ModelState.IsValid)
                {
                    dbContext.Processors.Add(processor);
                    dbContext.SaveChanges();
                    List<Processor> AllProcessors = dbContext.Processors.ToList();
                    return RedirectToAction("Dashboard");
                }
                else
                {
                    return View("New");
                }
            
        }

        [HttpGet("AdminPage")]
        public IActionResult AdminPage()
        {

                List<Processor> AllProcessors = dbContext.Processors.ToList();
                return View(AllProcessors);
            
        }





    }
}

Views/iLcwdMapper/AdminPage.cshtml
@model List<Processor>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>ADMIN PAGE</h1>
<a asp-action="Dashboard" asp-controller="iLcwdMapper" class="btn btn-warning" >HOME</a>
<a asp-action="new" asp-controller="iLcwdMapper" class="btn btn-warning">Add Processor</a>
<a asp-action="LogOut" asp-controller="Home" class="btn btn-warning" >LOGOUT</a>
<div id="ProcessorListBack">
    <div id="ProcessorList">
        <table class="table table-hover table-striped table-dark">
            <thead>
                <tr>
                <th>Processor</th>
                <th>Address</th>
                <th>City</th>
                <th>County</th>
                <th>Lat/Long</th>
                <th>Info</th>
                <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var w in @Model)
                {
                    <tr>
                        <td>@w.ProcessorName</td>
                        <td>@w.ProcessorAddress</td>
                        <td>@w.ProcessorCity, IL</td>
                        <td>@w.ProcessorCounty County</td>
                        <td>@w.LAT, @w.LNG</td>
                        <td>@w.ProcessorHours</td>
                        <td>
                        <a asp-action="destroy" asp-controller="iLcwdMapper" asp-route-ProcessorId="@w.ProcessorId">DELETE</a>
                        <a asp-action="edit" asp-controller="iLcwdMapper" asp-route-ProcessorId="@w.ProcessorId">EDIT</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
</body>
</html>

Views/iLcwdMapper/Dashboard.cshtml
@model List<Processor>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mainpage</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
    <style>
    * {
        margin: 0px;
        padding: 0px;
        box-sizing: border-box;
        font-family: Arial, Helvetica, sans-serif;
        @* outline: 1px dotted pink; *@
        }

    #wrapper {
        margin: 0px;
        width: 100%;
    }

    body {
        background-image: url(https://drive.google.com/uc?id=16NzF4qqJqZKpM5dn6D2NVlYaOiwnI7l8);
        background-color: lightgray;
        background-repeat: repeat;
        background-size: 50%;
    }
    

    nav {
        display: inline-block;
        background-color: 	#3F434C;
        width: 100%;
        color: white;
        margin-bottom: 40px;
        height: auto;
        padding-right: 20px;
    }
    .NavLink {
        background-color: #23252b;
        margin-top: 17px;
        margin-right: 4px;
    }
    #HeaderSub {
        margin-top: -30px;
        margin-left: 40px;
        margin-bottom: 10px;
        padding: 1px;
        width: 50%;
        height: auto;
        background-color: #3F434C;
    }

    #map {
        height: 700px;
        margin-top: -6px;
        margin-bottom: 40px;
    }

    html {
        height: 100%;
        margin: 0px;
        padding: 0px;
    }

    table {
        text-align: left;
        position: relative;
        border-collapse: collapse; 
    }

    td {
        color: smokegrey;
        font-size: 85%;
    }
tr.Head th{
    background: #23252b;
    color: Smokegrey;
}
    th {
        font-size: 100%;
        position: sticky;
        top: 0;
        background-color: red;
    }


    #ProcessorList {
        height: 730px;
        width: 97%;
        margin: auto;
        margin-bottom: 40px;
        overflow-y: scroll;
    }



    #ProcessorListTop {
        background-color: 	#3F434C;
        padding: 15px;
        padding-left: 20px;
        color: white;
    }
    #ProcessorListBack {
        background-color: 	#3F434C;
        padding-bottom: 30px;
        margin-bottom: 40px;
    }
    /* The CONTACT Modal (background) */
    .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }
    /* Modal Content */
    .modal-content {
    background-color: lightgrey;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 300px;
    }
    /* The Close Button */
    .close {
    color: black;
    float: right;
    font-size: 28px;
    font-weight: bold;
    }
    .close:hover,
    .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
    }


    #CWDInfo {
        width: 85%;
        margin: auto;
        height: 700px, auto;
        background-color: #3F434C;
        color: white;
        padding: 30px;
    }
    #LinksDiv {
        Display: block;
    }
    #InfoImg {
        Width: 100%;
    }
    #InfoImgDiv {
        display: inline-block;
        margin: 10px;
        width: 45%;
        text-align: justified;
        font-size: 10pt;
        padding: 1%;
        background-color: #23252b;

    }
    #InfoImgP {
        background-color: #23252b;
        margin: 1%;
        margin-bottom: -1%;
        width: 100%;
    }
    .InfoLinks {
        color: lightgrey;
        padding: 2px;
        margin-left: 10px;
        display: block;
    }
    #InfoDiv {
        vertical-align: top;
        width: 45%;
        display: inline-block;
        margin: 2%;
        margin-top: 6%;
    }


    footer {
        position: absolute;
        left: 0;
        right: 0;
        height: auto;
        background-color: 	#3F434C;
        color: white;
        padding: 10px;
        margin-top: 40px;
        margin-left: auto;
        margin-right: auto;
        width: 100%;
    }
    #footerdiv {
    }
    .FooterLink1 {
        margin-left: auto;
        margin-right: auto;
        margin-top: 15px;
        background-color: #23252b;
        display: block;
        width: 150px;
    }
    .FooterLink2 {
        margin-left: auto;
        margin-right: auto;
        margin-top: 100px;
        background-color: #23252b;
        display: block;
        width: 100px;
    }



    </style>

</head>
<body>
<div id="wrapper">

    <nav>
        <div class="w3-bar">
            <span id="Header" class="w3-bar-item  w3-padding-14 w3-xlarge">Illinois CWD Hunter Helper</span>
            <a href="#" id="myBtn" class="w3-bar-item w3-button w3-right w3-hide-small w3-hide-medium w3-padding-16 NavLink">Contact</a>
            <a href="#CWDInfo" class="w3-bar-item w3-button w3-right w3-hide-small w3-hide-medium w3-padding-16 NavLink">CWD Info</a>
            <a href="#ProcessorListTop" class="w3-bar-item w3-button w3-right w3-hide-small w3-hide-medium w3-padding-16 NavLink">Processor List</a>
            <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-padding-16 NavLink" onclick="myFunction()">&#9776;</a>
        </div>
        <div id="HeaderSub">An interactive map to help deer hunters find their nearest wild game butcher that can test for CWD infection! Scroll down to learn more about CWD.</div>

        <div id="dropdown" class="w3-bar-block w3-hide w3-hide-large NavLink">
            <a href="#" id="myBtnsml" class="w3-bar-item w3-button NavLink">Contact</a>
            <a href="#CWDInfo" class="w3-bar-item w3-button NavLink">CWD Info</a>
            <a href="#ProcessorListTop" class="w3-bar-item w3-button NavLink">Processor List</a>
        </div>
    </nav>

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-div">
            <span class="close">&otimes;</span>
            <h6>This web app was created by:</h6>
            <h2>Elliot McKinley</h2>
            <p><i class="fa fa-map-marker fa-fw w3-text-white w3-margin-right"></i> Chicago, US</p>
            <p><i class="fa fa-phone fa-fw w3-text-white w3-margin-right"></i> 773-562-4265</p>
            <i class="fa fa-envelope fa-fw w3-text-white w3-margin-right"> </i><a href="mailto:mckinleyelliot@gmail.com">ElliotMcKinley@gmail.com</a><p> </p>
            <i class="fa fa-linkedin-square fa-fw w3-text-white w3-margin-right"></i><a href="https://www.linkedin.com/in/elliot-mckinley">LinkedIn Profile</a>
        </div>
    </div>
</div>



    <div id="map"></div>



<div id="ProcessorListTop">
<h6>Below is a list of wild game butchers in Illinois that test venison for CWD infection.</h6>
</div>
<div id="ProcessorListBack">
    <div id="ProcessorList">
        <table class="w3-table table-hover table-striped table-dark">
            <thead>
                <tr class="Head">
                <th>Processor</th>
                <th>Address</th>
                <th>City</th>
                <th>County</th>
                <th>Lat/Long</th>
                <th>Info</th>
                </tr>
            </thead>
                <div id="TableHead">
                </div>
            <tbody>
                @foreach(var w in @Model)
                {
                    <tr>
                        <td>@w.ProcessorName</td>
                        <td>@w.ProcessorAddress</td>
                        <td>@w.ProcessorCity, IL</td>
                        <td>@w.ProcessorCounty County</td>
                        <td>@w.LAT, @w.LNG</td>
                        <td>@w.ProcessorHours</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="CWDInfo">
        <h1>CWD - Chronic Waste Disease</h1>
        <div id="InfoDiv">
<p>Chronic Waste Disease (CWD) is a prion disease that affects cervids, including the whitetail deer of Northern Illinois and Southern Wisconsin. CWD is fatal to animals, and there are no cures or vaccines. Humans cannot be infected with CWD, but the CDC and ILDNR recommend that hunters do not consume venison that has tested positive for CWD. The ILDNR recommends hunters have deer checked for CWD at any check-in station, or the participating meat processors listed above.

</p>

        </div>
        <div id="InfoImgDiv">
        <img id="InfoImg" alt="Deer with CWD" src="https://blogs.illinois.edu/files/7447/555051/118543.jpg"></img>
        <p id="InfoImgP">A young whitetail deer showing late signs of CWD. Deer can be infected with CWD for years before it impacts their health.</p>
        </div>
    <div id="LinksDiv">
        <h3>Reference Links</h3>
        <a class="InfoLinks" href="https://www.dnr.illinois.gov/programs/CWD/Pages/default.aspx">Illinois DNR CWD Management Program Information</a>
        <a class="InfoLinks" href="https://blogs.illinois.edu/view/7447/555051">Illinois Prarie Research Institute blog arrticle on CWD</a>
        <a class="InfoLinks" href="https://www.cdc.gov/prions/cwd/index.html">Center for Disease Control CWD Information</a>
        <a class="InfoLinks" href="http://cwd-info.org/cwd-the-basics/">CWD-Info.org - News source covering CWD developments nationwide</a>
    </div>
</div>


<footer>
    <div id="footerdiv">
        <a href="#" class="w3-button w3-padding-large w3-margin-bottom FooterLink1"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a><br>
        <a asp-action="SignIn" class="w3-button w3-padding-large w3-margin-bottom FooterLink2" asp-controller="Home">Admin</a>
    </div>
</footer>

<script> // Nav bar drop down for small screens
function myFunction() {
  var x = document.getElementById("dropdown");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

<script>
        var locations = [ 
        @foreach (var p in @Model){
            <text>
                {lat: @p.LAT, lng: @p.LNG, 
                info: "@p.ProcessorName", 
                address: "@p.ProcessorName<br> @p.ProcessorAddress<br> @p.ProcessorCity, IL <br> Hours: @p.ProcessorHours"},
            </text>
        }]
</script>

<script>
        function myMap() {  
        var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 41.100, lng: -89.496},
        zoom: 7
        });
        infoWindow = new google.maps.InfoWindow;
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            infoWindow.setPosition(pos);
            infoWindow.setContent('You are here!');
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } 
        else { // If Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
        var infowin = new google.maps.InfoWindow();
        var markers = locations.map(function(location, i) {
            var marker = new google.maps.Marker({
                position: location,
                label: location.info,
            });
            google.maps.event.addListener(marker, 'click', function(evt) {
                infowin.setContent(location.address);
                infowin.open(map, marker);
                
            })
            return marker;
        });

        var markerCluster = new MarkerClusterer(map, markers,
      {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
        }
</script>

<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>

<script async defer src=@ViewBag.ApiKey></script>

<script> //Modal Scripts
// Get the modal
var modal = document.getElementById("myModal");
// Get the button that opens the modal
var btn = document.getElementById("myBtn");
var btn2 = document.getElementById("myBtnsml");
// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];
// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "block";
}
btn2.onclick = function() {
  modal.style.display = "block";
}
// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>



</div>
</body>
</html>

Views/iLcwdMapper/Edit.cshtml
@using iLcwdMapper.Models
@model Processor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Edit info for @Model.ProcessorName</h1>
            <form asp-action="EditIt" asp-route-DishID="@Model.ProcessorId" method="post" asp-controller="iLcwdMapper">
            <label asp-for="ProcessorName"> Name:</label>
            <input asp-for="ProcessorName" value="@Model.ProcessorName"><br>

            <label asp-for="ProcessorAddress"></label>
            <input asp-for="ProcessorAddress"><br>

            <label asp-for="ProcessorCity"></label>
            <input asp-for="ProcessorCity"><br>

            <label asp-for="ProcessorCounty"></label>
            <input asp-for="ProcessorCounty"><br>

            <label asp-for="ProcessorHours"></label>
            <input asp-for="ProcessorHours"><br>

            <label asp-for="LAT"></label>
            <input asp-for="LAT"><br>

            <label asp-for="LNG"></label>
            <input asp-for="LNG"><br>

            <input type="submit" value="EDIT PROCESSOR" class="btn btn-outline-dark">
        </form><html>
    <div asp-validation-summary="All"></div>
    <a href="/processors">HOME</a>

</body>
</html>

Views/iLcwdMapper/New.cshtml
@model Processor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Add Processor</h1>
<div asp-validation-summary="All" class="text-danger"></div>

<form method="post" asp-action="Create" asp-controller="iLcwdMapper">

        <label asp-for="ProcessorCounty"></label>
        <input asp-for="ProcessorCounty"><br>

        <label asp-for="ProcessorName"></label>
        <input asp-for="ProcessorName"><br>

        <label asp-for="ProcessorAddress"></label>
        <input asp-for="ProcessorAddress"><br>

        <label asp-for="ProcessorCity"></label>
        <input asp-for="ProcessorCity"><br>

        <label asp-for="ProcessorHours"></label>
        <input asp-for="ProcessorHours"><br>

        <label asp-for="LAT"></label>
        <input asp-for="LAT"><br>

        <label asp-for="LNG"></label>
        <input asp-for="LNG"><br>

        <input type="submit" value="SUBMIT PROCESSOR" class="btn btn-outline-dark">
</form>
</body>
</html>